import { ArrowRight, Check, ClipboardList, Coins, RefreshCw, ShieldCheck } from "lucide-react";

import { PageContainer } from "@/components/layout/page-container";
import itAssetRecovery from "@/lib/services/it-asset-recovery";

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{eyebrow}</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">{title}</h2>{description ? <p className="mt-3 text-sm leading-relaxed text-secondary sm:text-base">{description}</p> : null}</div>;
}

const optionIcons = [Coins, RefreshCw, ShieldCheck];

export function ItAssetRecoveryServicePage() {
  return <PageContainer className="space-y-16 overflow-x-clip py-8 sm:space-y-20 sm:py-12">
    <section><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{itAssetRecovery.intro.eyebrow}</p><div className="mt-4 grid gap-8 border-b border-border-subtle pb-10 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div className="min-w-0"><h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-5xl">{itAssetRecovery.intro.title}</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-secondary sm:text-lg">{itAssetRecovery.intro.description}</p></div><div className="border-l-2 border-brand pl-4 text-sm font-semibold text-foreground sm:pl-5">{itAssetRecovery.intro.ctaText}</div></div></section>
    <section className="border-y border-border-subtle py-10"><SectionHeading {...itAssetRecovery.process} /><div className="mt-8 grid grid-cols-1 gap-px overflow-hidden border border-input-border bg-input-border md:grid-cols-3">{itAssetRecovery.process.steps.map((step) => <article key={step.number} className="bg-card p-5 sm:p-6"><p className="text-2xl font-bold text-brand">{step.number}</p><h3 className="mt-4 text-base font-semibold text-foreground">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{step.description}</p></article>)}</div></section>
    <section><SectionHeading {...itAssetRecovery.recoveryOptions} /><div className="mt-8 grid grid-cols-1 gap-4 lg:grid-cols-3">{itAssetRecovery.recoveryOptions.options.map((option, index) => { const Icon = optionIcons[index] ?? Coins; return <article key={option.id} className="border border-input-border bg-card p-5 shadow-sm sm:p-6"><Icon className="size-5 text-brand" aria-hidden /><p className="mt-5 text-2xl font-bold text-brand">{option.number}</p><h3 className="mt-2 text-lg font-semibold text-foreground">{option.title}</h3><p className="mt-3 text-sm leading-relaxed text-secondary">{option.description}</p><p className="mt-6 text-xs font-semibold uppercase tracking-[0.12em] text-brand">{option.action}</p></article>; })}</div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-[0.85fr_1.15fr]"><div><SectionHeading {...itAssetRecovery.assetTypes} /><div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2">{itAssetRecovery.assetTypes.categories.map((category) => <p key={category} className="flex items-start gap-2 text-sm text-secondary"><Check className="mt-0.5 size-4 shrink-0 text-brand" aria-hidden />{category}</p>)}</div></div><div className="border border-brand bg-brand/5 p-6 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Inventory first</p><p className="mt-4 text-2xl font-bold tracking-tight text-foreground">Know what you have before deciding what comes next.</p><p className="mt-4 text-sm leading-relaxed text-secondary">A clear inventory makes evaluation, recovery, trade-in, and resale decisions easier to compare.</p></div></section>
    <section><SectionHeading {...itAssetRecovery.benefits} /><div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{itAssetRecovery.benefits.points.map((point) => <article key={point.title} className="border border-input-border bg-card p-5 shadow-sm"><ClipboardList className="size-5 text-brand" aria-hidden /><h3 className="mt-5 text-sm font-semibold text-foreground">{point.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{point.description}</p></article>)}</div></section>
    <section className="border-t border-border-subtle pt-10"><SectionHeading eyebrow={itAssetRecovery.cta.eyebrow} title={itAssetRecovery.cta.title} description={itAssetRecovery.cta.description} /><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-brand"><span className="border border-brand px-4 py-3">{itAssetRecovery.cta.primaryButton}</span><span className="border border-input-border bg-card px-4 py-3 text-foreground">{itAssetRecovery.cta.secondaryButton}<ArrowRight className="ml-2 inline size-4" aria-hidden /></span></div></section>
  </PageContainer>;
}