import { ArrowRight, CircleCheck, Leaf } from "lucide-react";

import { PageContainer } from "@/components/layout/page-container";
import itRecyclingEnvironment from "@/lib/services/it-recycling-environment";

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{eyebrow}</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">{title}</h2>{description ? <p className="mt-3 text-sm leading-relaxed text-secondary sm:text-base">{description}</p> : null}</div>;
}

export function ItRecyclingEnvironmentServicePage() {
  return <PageContainer className="space-y-16 overflow-x-clip py-8 sm:space-y-20 sm:py-12">
    <section><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{itRecyclingEnvironment.intro.eyebrow}</p><div className="mt-4 grid gap-8 border-b border-border-subtle pb-10 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div className="min-w-0"><h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-5xl">{itRecyclingEnvironment.intro.title}</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-secondary sm:text-lg">{itRecyclingEnvironment.intro.description}</p></div><div className="border-l-2 border-brand pl-4 text-sm font-semibold text-foreground sm:pl-5">{itRecyclingEnvironment.intro.ctaText}</div></div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-[0.85fr_1.15fr]"><div className="border border-brand bg-brand/5 p-6 shadow-sm sm:p-8"><SectionHeading {...itRecyclingEnvironment.reuseFirst} /><p className="mt-6 border-l-2 border-brand pl-4 text-base font-semibold leading-relaxed text-foreground">{itRecyclingEnvironment.reuseFirst.highlight}</p></div><div><SectionHeading {...itRecyclingEnvironment.philosophy} /><p className="mt-6 border-l-2 border-brand pl-4 text-base font-semibold leading-relaxed text-foreground">{itRecyclingEnvironment.philosophy.highlight}</p></div></section>
    <section><SectionHeading {...itRecyclingEnvironment.whatWeSupport} /><div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{itRecyclingEnvironment.whatWeSupport.categories.map((category) => <article key={category.title} className="border border-input-border bg-card p-5 shadow-sm"><Leaf className="size-5 text-brand" aria-hidden /><h3 className="mt-5 text-base font-semibold text-foreground">{category.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{category.description}</p></article>)}</div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading {...itRecyclingEnvironment.whyRepair} /><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{itRecyclingEnvironment.whyRepair.points.map((point) => <article key={point.title} className="border border-input-border bg-card p-5 shadow-sm"><CircleCheck className="size-5 text-brand" aria-hidden /><h3 className="mt-4 text-sm font-semibold text-foreground">{point.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{point.description}</p></article>)}</div></section>
    <section className="border-y border-border-subtle py-10"><SectionHeading {...itRecyclingEnvironment.ourApproach} /><div className="mt-8 grid grid-cols-1 gap-px overflow-hidden border border-input-border bg-input-border sm:grid-cols-2 lg:grid-cols-4">{itRecyclingEnvironment.ourApproach.steps.map((step) => <article key={step.number} className="bg-card p-5"><p className="text-2xl font-bold text-brand">{step.number}</p><h3 className="mt-4 text-sm font-semibold text-foreground">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{step.description}</p></article>)}</div></section>
    <section className="border-t border-border-subtle pt-10"><SectionHeading eyebrow={itRecyclingEnvironment.cta.eyebrow} title={itRecyclingEnvironment.cta.title} description={itRecyclingEnvironment.cta.description} /><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-brand"><span className="border border-brand px-4 py-3">{itRecyclingEnvironment.cta.primaryButton}</span><span className="border border-input-border bg-card px-4 py-3 text-foreground">{itRecyclingEnvironment.cta.secondaryButton}<ArrowRight className="ml-2 inline size-4" aria-hidden /></span></div></section>
  </PageContainer>;
}