import { ArrowRight, Check, Cable, Router, Signal, Wifi } from "lucide-react";

import { PageContainer } from "@/components/layout/page-container";
import networkDevices from "@/lib/services/network-devices";

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{eyebrow}</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">{title}</h2>{description ? <p className="mt-3 text-sm leading-relaxed text-secondary sm:text-base">{description}</p> : null}</div>;
}

const problemIcons = [Router, Wifi, Signal, Cable];

export function NetworkDevicesServicePage() {
  return <PageContainer className="space-y-16 overflow-x-clip py-8 sm:space-y-20 sm:py-12">
    <section><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{networkDevices.intro.eyebrow}</p><div className="mt-4 grid gap-8 border-b border-border-subtle pb-10 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div className="min-w-0"><h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-5xl">{networkDevices.intro.title}</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-secondary sm:text-lg">{networkDevices.intro.description}</p></div><div className="border-l-2 border-brand pl-4 text-sm font-semibold text-foreground sm:pl-5">{networkDevices.intro.ctaText}</div></div></section>
    <section><SectionHeading {...networkDevices.commonProblems} /><div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">{networkDevices.commonProblems.problems.map((problem, index) => { const Icon = problemIcons[index] ?? Router; return <article key={problem.id} className="border border-input-border bg-card p-5 shadow-sm"><Icon className="size-5 text-brand" aria-hidden /><p className="mt-5 text-2xl font-bold text-brand">{problem.number}</p><h3 className="mt-2 text-base font-semibold text-foreground">{problem.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{problem.description}</p></article>; })}</div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-[0.8fr_1.2fr]"><SectionHeading {...networkDevices.networkSupport} /><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{networkDevices.networkSupport.services.map((service) => <article key={service.id} className="border border-input-border bg-card p-5 shadow-sm"><h3 className="text-base font-semibold text-foreground">{service.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{service.description}</p></article>)}</div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-[1.1fr_0.9fr]"><div><SectionHeading {...networkDevices.supportedEquipment} /><div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2">{networkDevices.supportedEquipment.categories.map((category) => <p key={category} className="flex items-start gap-2 text-sm text-secondary"><Check className="mt-0.5 size-4 shrink-0 text-brand" aria-hidden />{category}</p>)}</div></div><div className="border border-brand bg-brand/5 p-6 shadow-sm sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Connected support</p><p className="mt-4 text-2xl font-bold tracking-tight text-foreground">A clearer path from weak signal to reliable network.</p><p className="mt-4 text-sm leading-relaxed text-secondary">We assess the devices, connection, cabling, and environment together so the fix addresses the real cause.</p></div></section>
    <section className="border-y border-border-subtle py-10"><SectionHeading {...networkDevices.repairProcess} /><div className="mt-8 grid grid-cols-1 gap-px overflow-hidden border border-input-border bg-input-border sm:grid-cols-2 lg:grid-cols-4">{networkDevices.repairProcess.steps.map((step) => <article key={step.number} className="bg-card p-5"><p className="text-2xl font-bold text-brand">{step.number}</p><h3 className="mt-4 text-sm font-semibold text-foreground">{step.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{step.description}</p></article>)}</div></section>
    <section className="border-t border-border-subtle pt-10"><SectionHeading eyebrow={networkDevices.cta.eyebrow} title={networkDevices.cta.title} description={networkDevices.cta.description} /><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-brand"><span className="border border-brand px-4 py-3">{networkDevices.cta.primaryButton}</span><span className="border border-input-border bg-card px-4 py-3 text-foreground">{networkDevices.cta.secondaryButton}<ArrowRight className="ml-2 inline size-4" aria-hidden /></span></div></section>
  </PageContainer>;
}