import { ArrowRight, Check, HardDrive, Network, Settings, ShieldCheck } from "lucide-react";

import { PageContainer } from "@/components/layout/page-container";
import operatingSystemInstallation from "@/lib/services/operating-system-installation";

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{eyebrow}</p><h2 className="mt-3 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">{title}</h2>{description ? <p className="mt-3 text-sm leading-relaxed text-secondary sm:text-base">{description}</p> : null}</div>;
}

const serviceIcons = [Settings, HardDrive, Network];

export function OperatingSystemInstallationServicePage() {
  return <PageContainer className="space-y-16 overflow-x-clip py-8 sm:space-y-20 sm:py-12">
    <section><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">{operatingSystemInstallation.intro.eyebrow}</p><div className="mt-4 grid gap-8 border-b border-border-subtle pb-10 lg:grid-cols-[1.25fr_0.75fr] lg:items-end"><div className="min-w-0"><h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-5xl">{operatingSystemInstallation.intro.title}</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-secondary sm:text-lg">{operatingSystemInstallation.intro.description}</p></div><div className="border-l-2 border-brand pl-4 text-sm font-semibold text-foreground sm:pl-5">{operatingSystemInstallation.intro.ctaText}</div></div></section>
    <section><SectionHeading eyebrow="OUR SERVICES" title="Practical support for computers and connected devices." description="Choose the service your system needs, from a clean operating system setup to a tuned-up PC or a working network environment." /><div className="mt-8 grid grid-cols-1 gap-4 lg:grid-cols-3">{operatingSystemInstallation.services.map((service, index) => { const Icon = serviceIcons[index] ?? Settings; return <article key={service.id} className="border border-input-border bg-card p-5 shadow-sm"><Icon className="size-5 text-brand" aria-hidden /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.15em] text-brand">{service.eyebrow}</p><h3 className="mt-2 text-lg font-semibold text-foreground">{service.title}</h3><p className="mt-2 text-sm leading-relaxed text-secondary">{service.description}</p><ul className="mt-5 space-y-2 border-t border-border-subtle pt-4">{service.items.map((item) => <li key={item} className="flex items-start gap-2 text-sm text-secondary"><Check className="mt-0.5 size-4 shrink-0 text-brand" aria-hidden /><span className="break-words">{item}</span></li>)}</ul></article>; })}</div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-2"><div className="border border-input-border bg-card p-6 shadow-sm sm:p-8"><SectionHeading {...operatingSystemInstallation.operatingSystems} /><div className="mt-6 flex flex-wrap gap-2">{operatingSystemInstallation.operatingSystems.platforms.map((platform) => <span key={platform} className="border border-input-border bg-background px-3 py-2 text-sm text-secondary">{platform}</span>)}</div></div><div className="border border-brand bg-brand/5 p-6 shadow-sm sm:p-8"><SectionHeading {...operatingSystemInstallation.networkServices} /><div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2">{operatingSystemInstallation.networkServices.services.map((service) => <p key={service} className="flex items-start gap-2 text-sm text-secondary"><Network className="mt-0.5 size-4 shrink-0 text-brand" aria-hidden />{service}</p>)}</div></div></section>
    <section className="border-t border-border-subtle pt-10"><SectionHeading eyebrow={operatingSystemInstallation.cta.eyebrow} title={operatingSystemInstallation.cta.title} description={operatingSystemInstallation.cta.description} /><div className="mt-6 flex flex-wrap gap-3 text-sm font-semibold text-brand"><span className="border border-brand px-4 py-3">{operatingSystemInstallation.cta.primaryButton}</span><span className="border border-input-border bg-card px-4 py-3 text-foreground">{operatingSystemInstallation.cta.secondaryButton}<ArrowRight className="ml-2 inline size-4" aria-hidden /></span></div></section>
  </PageContainer>;
}